### ISSUE TITLE
Dropouts with MAX98357A

### ISSUE THREAD

**Issue by pr-boh** [Arielhh/ESP32-Radio-Internet-With-TouchScreen-Display#2]
I set up your fascinating project. but unfortunately I have dropouts every little while (10 to 20 seconds for about 1s). It looks like a short interrupt. Stream starts again where it stops.
No matter what station I use.
I am using a T-Display-S3-Touch with a MAX98357A.
Do you have an idea what the cause could be?

**Comment by MicroMkr** [comment]
Hi, yes you are right, sorry for that. The issue is related to the Audio library which is part of the code. 
I just found that in order to fix it I will need to port the code to Platformio. I am planning to do that but it will take some time.

**Comment by pr-boh** [comment]
Thank you for the quick answer. I look forward to that, because I like your solution for a small but powerful internet-radio very much.

**Comment by MicroMkr** [comment]
new fixed version is avaliable
