### ISSUE TITLE
After Boot not able to proceed with config to local wifi network

### ISSUE THREAD

**Issue by smashim** [Arielhh/ESP32-Radio-Internet-With-TouchScreen-Display#3]
My boot-up sequence not following provided instructions after flashing the device.

Upon boot up after flashing LILGO ESPS3 with files per instructions, the display showed it successfully scaned avail network and then jumped right to "connecting to xinyuanianzi...." followed by "connection timed out, start smartconig, wait for smartconfig....
Please use EspTouch Apps to connect to the distribution network"

Not sure where to go with this but never had a chance to try to find the "AH_Radio" published SSID from the device on my phone to configure to my local network.

pls advise

pete

**Comment by MicroMkr** [comment]
It looks like the flashing process was not initiated /completed. Make sure
to choose the active serial com port on the right bottom of the flashing tool
screen. While flashing you should see the green flashing bar progressing
until the flashing process complete. Check also that you choose the right files and the flash address are correct. I am planning making a video on the installation process in the near future.

**Comment by smashim** [comment]
Now getting "16-bin file overlap" so making some progress

C:\Users\Lenovo\Downloads\touchSlider111Stereo\touchSlider111.ino.bootloader.bin
1 kill
C:\Users\Lenovo\Downloads\touchSlider111Stereo
C:\Users\Lenovo\Downloads\touchSlider111Stereo\touchSlider111.ino.partitions.bin
2 kill
C:\Users\Lenovo\Downloads\touchSlider111Stereo
C:\Users\Lenovo\Downloads\touchSlider111Stereo\touchSlider111.ino.bin
3 kill
C:\Users\Lenovo\Downloads\touchSlider111Stereo
C:\Users\Lenovo\Downloads\boot_app0.bin
4 kill
test offset :  0 0x0
case ok
test offset :  32768 0x8000
case ok
test offset :  65536 0x10000
case ok
test offset :  57344 0xe000
case ok
test offset :  0 0x0
case ok
test offset :  32768 0x8000
case ok
test offset :  65536 0x10000
case ok
test offset :  57344 0xe000
case ok
[2024-01-07 15:21:29,171][ESP8266Loader_spi[1]][espDownloader.py][line:741][ERROR]:
no log file output ...

**Comment by MicroMkr** [comment]
Can you share a screenshot?

**Comment by smashim** [comment]
Arieill - I managed to get it to load this time.....have no idea was the issue ( I guess com port related) was so now I have configured the wifi on the device and reboot. Access the IP address with browser and have the Radio Station Manager so now I just need to follow the rest of your instructions to get some url radio stations stored !  It looks like a great project so hopefully I am almost there.

Thanks again...... great little project!

**Comment by smashim** [comment]
I am able to load a station but and the target device browser window look like it stored a station but the device itself screen is blank. I get the boot up radio symbol but then the LLYGO display goes blank and stays blank. Am I missing a step ?  I may not have the touch version of the LILYGO S3 !!!!  Going to order another one to make sure I have the touch version. That could be my issue now..... noob mistake but will confirm and let you know

**Comment by smashim** [comment]
![Screenshot 2024-01-07 at 7 19 29 PM](https://github.com/Arielhh/ESP32-Radio-Internet/assets/3358594/27282acc-713e-4980-9dec-5cafd1ae75e7)

**Comment by MicroMkr** [comment]
Try for example the following stations
Roma Radio, http://nr9.newradio.it:9371/stream
RAI Radio 2, http://icestreaming.rai.it/2.mp3
RAI Radio 1, http://icestreaming.rai.it/1.mp3

You can use
https://streamurl.link/ to find the links to the radio stations you like.

**Comment by smashim** [comment]
Arielhh,

OK, I got the correct LLGO ESP-S3 TOUCH version board in and connected to a
PCM5102A Dac module and everything works. See connection diagram below.
Thanks for the help!

I am going to play around and provide some user feature suggestions if you
don't mind (one example is that I noticed that the display times-out and
you have to touch the display to get the display to come back on but in
doing so it pauses the active audio stream when you do that and takes a few
seconds to come back. I would like the display to just stay on - just a
personal preference)

Great work and I have some plans to make some units for relatives!



[image: Screenshot 2024-01-09 at 6.55.54 PM.png]

**Comment by MicroMkr** [comment]
The delay you are describing is because you press on the middle of the screen which causes the radio to reconnect to the station. If you only want to light the screen press momentary on the right bottom side of the screen. 
The reason the screen turns of after few seconds is for preserving battery (I designed it to work on a battery). It will be nice to see photos of your final results. This will inspire others to build it as well.

**Comment by smashim** [comment]
Thanks...

Will go back and read your operating description (was too focused on just
getting it working).

I am noticing also that the device only works with internet radio stations
that have an auto-player type setup so I am trying to find more stations
that work that way to build my list.

At least I am off and running now and having fun playing with this.

I will be happy to share more once I have the unit in a final case and
other info that may be of interest to others.

pete
