### ISSUE TITLE
Support for UTF-8

### ISSUE THREAD

**Issue by kri164** [Arielhh/ESP32-Radio-Internet-With-TouchScreen-Display#5]
Hello Ariel,

can you add support for non-english radio station names?
When I entered some letters with diacritics signs, it is displayed wrongly.

For example

`Rádio Čas Rock,http://icecast7.play.cz/casrock128.mp3`

Thank you

**Comment by MicroMkr** [comment]
I don't have plans to make it at the moment. But, I will add it to the to-do list.
